Added MemoryStreamExtensions.cs
JustNrik/NetUtilities pull request #30
Opened 2021-01-24 04:22 UTC by AraHaan

This will help new people to clear their MemoryStreams a lot easier (possibly before disposing so it is not hard on GC with large MemoryStreams that might be on GC 2 or even LOH).

2021-03-13 18:36 UTC, JustNrik commented
Don't set the capacity to 0 just like that, if the user wants to keep using the stream after clearing it, it will allocate a new array that will be resized on demand, and if the array was already big enough to be in the LOH and the user keeps using it, then it will hurt performance a lot as it will be resized many times. Keep in mind that Clearing the stream doesn't meant that he won't use the stream anymore.

Instead, make some changes to allow the user to be more explicit with their intentions, like adding a parameter to set the new capacity, so you set it to 0 for the clean up and then you set it to the new capacity instead of leaving it at zero.

2021-03-13 18:37 UTC, JustNrik requested changes
Don't set the capacity to 0 just like that, if the user wants to keep using the stream after clearing it, it will allocate a new array that will be resized on demand, and if the array was already big enough to be in the LOH and the user keeps using it, then it will hurt performance a lot as it will be resized many times. Keep in mind that Clearing the stream doesn't meant that he won't use the stream anymore.

Instead, make some changes to allow the user to be more explicit with their intentions, like adding a parameter to set the new capacity, so you set it to 0 for the clean up and then you set it to the new capacity instead of leaving it at zero.

2021-03-14 00:38 UTC, AraHaan commented on NetUtilities/System/IO/MemoryStreamExtensions.cs
> +            Array.Clear(ms.GetBuffer(), 0, ms.GetBuffer().Length);
I changed this as not sure if Array.Clear would only change only the local byte array, or the array owned by the MemoryStream when I did it the other way 😅. This way makes it more explicit but I feel I could save the length to a local variable too,

2021-03-14 00:40 UTC, AraHaan commented
Should I also wrap ``SetLength`` too?

2021-03-18 21:27 UTC, JustNrik approved these changes

2021-03-18 21:27 UTC, merged